---
title: "Homework 4"
author: "Vinny Sriram, Lee-Ann Kao, Jennifer Centa"
date: "2024-03-04"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**We are working with the a Data Set that tracks the democraticness, economic conditions, and foreign aid, of post colonial countries across time. The group members are Vinny Sriram, Lee-Ann Kao, and Jennifer Centa. Our emails are vinny.sriram@yale.edu, lee-ann.kao@yale.edu, and jennifer.centa@yale.edu.**

```{r}
library(MASS)
library(biotools)
library(klaR)
library(car)
library(ggplot)
```

### Set-Up
```{r}
data <- read.csv("data.csv")
table(data$dd, data$region)
data <- subset(data, region %in% c("East Asia and Pacific", "Latin America and Caribbean", "South Asia", "Sub-Saharan Africa"))
data$dd <- as.factor(data$dd)
data$region <- as.factor(data$region)
```

### Question 1
```{r}
# Interaction plot for Log Exports
interaction.plot(data$dd, data$region, data$logexp,
                 lwd = 3, col = c("red", "blue", "green", "black"),
                 trace.label = "Region", xlab = "Regime", ylab = "Log Exports",
                 main = "Interaction Plot for Log Exports")

# Interaction plot for Foreign Direct Investment
interaction.plot(data$dd, data$region, data$fdi,
                 lwd = 3, col = c("red", "blue", "green", "black"),
                 trace.label = "Region", xlab = "Regime", ylab = "FDI",
                 main = "Interaction Plot for Foreign Direct Investment")

# Interaction plot for Log Imports
interaction.plot(data$dd, data$region, data$logimp,
                 lwd = 3, col = c("red", "blue", "green", "black"),
                 trace.label = "Region", xlab = "Regime", ylab = "Log Imports",
                 main = "Interaction Plot for Log Imports")

# Interaction plot for Log GDP per Capita
interaction.plot(data$dd, data$region, data$loggdpc,
                 lwd = 3, col = c("red", "blue", "green", "black"),
                 trace.label = "Region", xlab = "Regime", ylab = "Log GDP per Capita",
                 main = "Interaction Plot for Log GDP per Capita")


```


### Question 2
```{r}
options(contrasts = c("contr.sum", "contr.poly"))

MAOV <- lm(cbind(logexp, fdi, logimp, loggdpc) ~ dd * region, data = data)

# Multivariate and univariate results
summary(Anova(MAOV, type = 3), univariate = T)
```

### Question 3
```{r}
options(contrasts = c("contr.treatment", "contr.poly"))

levels(data$dd)
MAOV2<- lm(cbind(logexp, fdi, logimp, loggdpc) ~ dd, data = data)
linearHypothesis(MAOV2, "-ddDictatorship = 0")

logexpANOVA <- lm(logexp ~ dd, data = data)
linearHypothesis(logexpANOVA, "-ddDictatorship = 0")

logimpANOVA <- lm(logimp ~ dd, data = data)
linearHypothesis(logimpANOVA, "-ddDictatorship = 0")


```

### Question 4
```{r}

# Create scatter plots for each covariate-response pair
plot1 <- ggplot(data, aes(x = EUaid, y = logexp)) +
  geom_point() +
  geom_smooth(method = "lm") +  
  ggtitle("EUaid vs logexp")

plot2 <- ggplot(data, aes(x = EUaid, y = fdi)) +
  geom_point() +
  geom_smooth(method = "lm") +
  ggtitle("EUaid vs fdi")

plot3 <- ggplot(data, aes(x = EUaid, y = logimp)) +
  geom_point() +
  geom_smooth(method = "lm") +
  ggtitle("EUaid vs logimp")

plot4 <- ggplot(data, aes(x = EUaid, y = loggdpc)) +
  geom_point() +
  geom_smooth(method = "lm") +
  ggtitle("EUaid vs loggdpc")

library(gridExtra)
grid.arrange(plot1, plot2, plot3, plot4, ncol = 2)

options(contrasts = c("contr.sum", "contr.poly"))

#Fit the model
MAOVMod2 <- lm(cbind(logexp, fdi, logimp, loggdpc) ~ dd * region +  EUaid, data = data)

#Multivariate results and univariate results with with type 3 Sum of squares
summary(Anova(MAOVMod2, type = 3), univariate = T)

mod1 <- lm(logexp ~ region + dd + region*dd + EUaid, data = data)
mod2 <- lm(fdi ~ region + dd + region*dd + EUaid, data = data)
mod3 <- lm(logimp ~ region + dd + region*dd + EUaid, data = data)
mod4 <- lm(loggdpc ~ region + dd + region*dd + EUaid, data = data)

#Type I Sum of Squares
summary.aov(mod1)
summary.aov(mod2)
summary.aov(mod3)
summary.aov(mod4)

#Check residuals
CSQPlot(MAOVMod2$residuals, label = "Residuals from GLM")
```

### Question 5
```{r}
#Check model assumptions by making a chi-square quantile plot of the residuals.
# Modify your model as appropriate based on your findings.

#Check residuals
CSQPlot(MAOVMod2$residuals, label = "Residuals from GLM")

modexp <- lm(logexp ~ dd * region +  EUaid, data = data)
plot(modexp, which = c(1,2), pch = 19, col = 'red')

modfdi <- lm(fdi ~ dd * region +  EUaid, data = data)
plot(modfdi, which = c(1,2), pch = 19, col = 'orange')

modlogimp <- lm(logimp ~ dd * region +  EUaid, data = data)
plot(modlogimp, which = c(1,2), pch = 19, col = 'yellow')

modloggdpc <- lm(loggdpc ~ dd * region +  EUaid, data = data)
plot(modloggdpc, which = c(1,2), pch = 19, col = 'blue')

data$newfdi <- data$fdi - min(data$fdi, na.rm = T)*1.01
modfdi2 <- lm(newfdi ~ dd * region +  EUaid, data = data)
BC <- boxcox(modfdi2, optimize = T)
(lambda <- BC$x[which.max(BC$y)])

data$newfdi <- (data$fdi - min(data$fdi, na.rm = T)*1.01)^0.3

modmin2 <- lm(newfdi ~ dd * region +  EUaid, data = data)
plot(modmin2, which = c(1, 2), col = 'blue', pch = 19)

#Fit the model
Mod2 <- lm(cbind(logexp, newfdi, logimp, loggdpc) ~ dd * region +  EUaid, data = data)

#Multivariate and univariate results with type 3 Sum of squares
summary(Anova(Mod2, type = 3), univariate = T)

CSQPlot(Mod2$residuals, label = "Residuals from Data")

```

### Question 6
```{r}
library(vegan)
(mrpp1 <- mrpp(data[,c("EUaid", "CIRI", "educm", "logexp", "fdi", "logimp", "loggdpc", "demregion")], as.factor(data$country)))
```
